packages:
  - 'apps/*'
  - 'packages/*'
  - 'infra/local'

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - argon2
  - esbuild
  - sharp
  - '@nestjs/core'
  - unrs-resolver
  - '@embedded-postgres/windows-x64'
  - '@embedded-postgres/linux-x64'
  - '@embedded-postgres/darwin-arm64'
  - '@embedded-postgres/darwin-x64'
